import type { Metadata } from 'next'
import './globals.css'
import Header from './_components/ui/header'
import { Providers } from './_components/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className='flex min-h-lvh flex-col justify-between px-4 font-sans
 antialiased transition md:px-10 lg:px-20 '
      >
        <Providers>
          <Header />
          <main className='mx-auto h-full max-w-7xl'>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
